.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

chore: Add template

---

raiden/src/lib.rs

Add Into/From attr to `bool` and `HashSet<String>`

feat: Add bool and HashSet<String>

---

raiden-derive/src/ops/put.rs
raiden/tests/all/put.rs

chore: Add put test with uuid and fix putitem owner

---

raiden-derive/src/ops/put.rs
raiden/src/lib.rs

Fix builder path

---

raiden-derive/src/ops/put.rs
raiden/src/lib.rs

fix: builder

---

raiden-derive/src/ops/put.rs
raiden/examples/put.rs
raiden/src/ops/mod.rs
raiden/src/ops/put.rs

Return new value when put
None
None
None

feat: Return new value when put

---

raiden-derive/src/ops/put.rs
raiden/examples/put.rs

feat: Add into for uuid

---

raiden-derive/src/ops/get.rs
raiden-derive/src/ops/put.rs
raiden-derive/src/ops/query.rs
raiden/examples/put.rs

fix: make outout fields public

---

raiden-derive/src/lib.rs
raiden-derive/src/ops/put.rs
raiden/src/id_generator/mod.rs
raiden/src/lib.rs

fix: create id generator

---

README.md

Add requirements and instructions to setup for developers.
N/A
N/A
N/A

chore: Add section for developers in README

---

raiden/src/id_generator/mod.rs

fix: Fix uuid by env variable

---

raiden-derive/src/attribute/names.rs
raiden-derive/src/lib.rs
raiden-derive/src/ops/get.rs
raiden-derive/src/ops/put.rs
raiden-derive/src/ops/query.rs
raiden-derive/src/ops/update.rs
raiden-derive/src/rename/mod.rs
raiden/examples/query_rename.rs
raiden/tests/all/query.rs
setup/index.js

Apply `rename_all` to attribute name
NA
NA
NA

fix: Fixed a value of attrName when using rename_all

---

makefile
raiden-derive/src/lib.rs
raiden-derive/src/ops/get.rs
raiden-derive/src/ops/mod.rs
raiden-derive/src/ops/put.rs
raiden-derive/src/ops/transact_write.rs
raiden/examples/transact_write.rs
raiden/src/errors/mod.rs
raiden/src/ops/mod.rs
raiden/src/ops/transact_write.rs
raiden/tests/all/transact_write.rs

Add minimum transaction write.
NA
NA
NA

Add transaction write

---

raiden-derive/src/ops/transact_write.rs
raiden/tests/all/transact_write.rs
setup/index.js

Add table suffix for transact write

---

raiden/src/lib.rs
raiden/tests/all/put.rs

Add converter for `HashSet<A>` and `Vec<A>`
NA
NA
NA

Append from to attr

---

raiden-derive/src/ops/query.rs

Impl scan_index_forward
https://docs.aws.amazon.com/ja_jp/amazondynamodb/latest/developerguide/Query.html
NA
NA

feat: Impl scan_index_forward

---

raiden/src/lib.rs
raiden/tests/all/get.rs
raiden/tests/all/put.rs
setup/index.js

fix: string set to able to set custom string set and get item properly

---

raiden-derive/src/lib.rs
raiden-derive/src/ops/query.rs
raiden-derive/src/ops/update.rs
raiden/examples/update.rs
raiden/src/errors/mod.rs
raiden/src/ops/mod.rs
raiden/src/ops/update.rs

Improve update return values
NA
NA
NA

fix: update return values

---

raiden-derive/src/ops/update.rs
raiden/src/ops/update.rs
raiden/tests/all/update.rs

- Support `condition` for update.
- Set return values to None, default.
NA
NA
NA

fix: improve update return values

---

raiden-derive/src/ops/update.rs

fix: clippy error

---

raiden-derive/src/ops/delete.rs
raiden/src/errors/mod.rs
raiden/tests/all/delete.rs
setup/index.js

fix: delete return value

---

raiden-derive/src/condition/builder.rs
raiden-derive/src/ops/delete.rs
raiden/src/condition/mod.rs
raiden/tests/all/delete.rs
setup/index.js

Support `condition` for `delete` #42 
NA
NA
NA

fix: Support condition for `delete item` #42

---

README.md
raiden-derive/src/ops/batch_get.rs
raiden/examples/hello.rs
raiden/src/errors/mod.rs
raiden/src/ops/batch_get.rs
raiden/src/ops/mod.rs
raiden/tests/all/batch_get.rs
raiden/tests/all/mod.rs
setup/index.js

See https://github.com/raiden-rs/raiden/issues/14 for the detail.
See https://github.com/raiden-rs/raiden/issues/14 for the detail.
N/A
N/A

Implement `batch_get` for the client.

---

.github/workflows/ci.yml
raiden-derive/src/attribute/names.rs
raiden-derive/src/condition/builder.rs
raiden-derive/src/finder/mod.rs
raiden-derive/src/lib.rs
raiden-derive/src/ops/put.rs
raiden-derive/src/ops/shared.rs
raiden-derive/src/ops/update.rs
raiden-derive/src/rename/mod.rs
raiden-derive/src/sort_key/mod.rs
raiden/src/condition/mod.rs
raiden/src/key_condition/mod.rs
raiden/src/lib.rs
raiden/src/next_token/mod.rs
raiden/src/update_expression/set.rs

Used Clippy and removed the unnecessary clone. I didn't fix the unused fields and warning in tests and examples directories. They will seem to be used near the future.
N/A
N/A
N/A

chore: Used clippy and removed the unnecessary clone

---

raiden-derive/src/ops/update.rs
raiden/src/update_expression/add.rs
raiden/src/update_expression/mod.rs
raiden/src/update_expression/set.rs
raiden/tests/all/update.rs

Improve `update add` interafce.
NA
NA
NA

fix: improve add expression

---

raiden-derive/src/ops/transact_write.rs

fix: improve add for tx

---

raiden-derive/src/ops/batch_get.rs

fix table name to use prefix and suffix.
NA
NA
NA

fix: table name

---

raiden-derive/src/ops/update.rs
raiden/src/lib.rs
raiden/src/update_expression/add.rs
raiden/tests/all/update.rs
setup/index.js

See https://github.com/raiden-rs/raiden/issues/57
NA
NA
NA

fix: empty behavior in update

---

raiden-derive/src/ops/update.rs

fix: error

---

raiden-derive/src/ops/query.rs

add desc /asc instaed of scan_index_forward
NA
NA
NA

fix: sorting method

---

raiden-derive/src/ops/transact_write.rs
raiden-derive/src/ops/update.rs
raiden/src/update_expression/add.rs
raiden/src/update_expression/delete.rs
raiden/src/update_expression/mod.rs
raiden/src/update_expression/set.rs
raiden/tests/all/update.rs
setup/index.js

Improve delete expression in update
NA
Na
NA

Fix update delete expression

---

raiden/tests/all/update.rs
setup/index.js

spec: Add test

---

raiden-derive/src/ops/transact_write.rs
raiden-derive/src/ops/update.rs
raiden/src/lib.rs
raiden/src/update_expression/add.rs
raiden/src/update_expression/delete.rs
raiden/src/update_expression/mod.rs
raiden/src/update_expression/set.rs
raiden/tests/all/put.rs
raiden/tests/all/update.rs
setup/index.js

Use empty instead of null.
cose https://github.com/raiden-rs/raiden-dynamo/issues/64
NA
NA
NA

Improve empty behavior

---

raiden/src/errors/mod.rs

fix: remove unused error

---

raiden-derive/src/ops/query.rs
raiden/src/ops/query.rs
raiden/tests/all/query.rs
raiden/tests/all/rename.rs

fix: expose next_token in query

---

Cargo.lock
README.md
raiden-derive/Cargo.toml
raiden-derive/src/finder/mod.rs
raiden-derive/src/lib.rs
raiden-derive/src/ops/mod.rs
raiden-derive/src/ops/put.rs
raiden-derive/src/ops/shared.rs
raiden/Cargo.toml
raiden/examples/put.rs
raiden/examples/transact_write.rs
raiden/src/lib.rs
raiden/tests/all/put.rs
raiden/tests/all/transact_write.rs

#19 Use safe builder.
NA
NA
NA

use safe builder

---

README.md

T/O
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Operations_Amazon_DynamoDB.html
N/A
N/A

Add section of supported APIs

---

Cargo.lock
raiden/Cargo.toml

builder 0.0.5

---

raiden-derive/src/ops/put.rs
raiden-derive/src/ops/update.rs
raiden/src/ops/transact_write.rs

Add retry to tx write, put, and update
NA
NA
NA

Add retry to tx write, put, and update

---

raiden/src/ops/transact_write.rs
raiden/tests/all/get.rs
raiden/tests/all/transact_write.rs

feat: Add txWrite retry feature

---

raiden-derive/src/lib.rs
raiden/examples/get_with_retries.rs
raiden/tests/all/get.rs

fix: builder ownership

---

raiden-derive/src/ops/batch_get.rs
raiden-derive/src/ops/query.rs
raiden-derive/src/ops/scan.rs
raiden/tests/all/batch_get.rs
raiden/tests/all/query.rs
raiden/tests/all/scan.rs

Apply project-expression for scan, batch_get, and query
https://github.com/raiden-rs/raiden-dynamo/issues/30
NA
NA

Applys projection-expression for some methods

---

README.md
raiden-derive/src/ops/batch_get.rs
raiden/tests/all/batch_get.rs
setup/index.js
setup/yarn.lock

If batchGetItem run into 16MB limitation, retry automatically.
NA
NA
NA

feat: Improve batch get

---

Cargo.lock
raiden-derive/src/ops/transact_write.rs
raiden/src/ops/transact_write.rs
raiden/tests/all/transact_write.rs
setup/index.js

feat: Support tx delete

---

raiden/tests/all/update.rs
setup/index.js

spec: Add update remove test

---

Cargo.lock
raiden/Cargo.toml

Upgrade insta to 1.5.2

---

raiden-derive/src/ops/batch_get.rs
raiden-derive/src/ops/get.rs
raiden-derive/src/ops/put.rs
raiden-derive/src/ops/query.rs
raiden-derive/src/ops/scan.rs
raiden/examples/get_with_reserved.rs
raiden/examples/get_with_retries.rs
raiden/examples/hello.rs
raiden/examples/last_key.rs
raiden/examples/put.rs
raiden/examples/query_rename.rs
raiden/examples/transact_write.rs
raiden/tests/all/batch_get.rs

fix: clippy errors

---

Cargo.lock
raiden/src/lib.rs
raiden/tests/all/get.rs
setup/index.js

fix: Support float convertor

---

raiden/src/lib.rs

Add number set convertor
NA
NA
NA

fix: #32 Support number set

---

raiden/src/key_condition/mod.rs
raiden/tests/all/query.rs
raiden/tests/all/scan.rs
setup/index.js

spec: Add size limitation test

---

.github/workflows/ci.yml
raiden-derive/src/finder/mod.rs
raiden-derive/src/key/mod.rs
raiden/examples/delete.rs
raiden/examples/get_with_reserved.rs
raiden/examples/get_with_retries.rs
raiden/examples/hello.rs
raiden/examples/last_key.rs
raiden/examples/put.rs
raiden/examples/query.rs
raiden/examples/query_rename.rs
raiden/examples/scan.rs
raiden/examples/transact_write.rs
raiden/examples/update.rs
raiden/tests/all/batch_get.rs
raiden/tests/all/delete.rs
raiden/tests/all/get.rs
raiden/tests/all/put.rs
raiden/tests/all/query.rs
raiden/tests/all/rename.rs
raiden/tests/all/rename_all.rs
raiden/tests/all/scan.rs
raiden/tests/all/transact_write.rs
raiden/tests/all/update.rs

fix: errors

---

Cargo.lock
raiden-derive/src/condition/builder.rs
raiden-derive/src/condition/mod.rs
raiden-derive/src/ops/batch_get.rs
raiden-derive/src/ops/delete.rs
raiden-derive/src/ops/get.rs
raiden-derive/src/ops/put.rs
raiden-derive/src/ops/query.rs
raiden-derive/src/ops/scan.rs
raiden-derive/src/ops/transact_write.rs

fix: expose some builder method

---

raiden/Cargo.toml

Reverts raiden-rs/raiden-dynamo#146

Revert "fix(deps): update rust crate rusoto_dynamodb_rustls to 0.47"

---

raiden/src/condition/mod.rs
raiden/tests/all/condition.rs
raiden/tests/all/update.rs
setup/deps.ts

Implement the "or" ConditionExpression.
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html

add or condition

---

README.md
raiden-derive/src/ops/query.rs
raiden-derive/src/ops/scan.rs
raiden/examples/delete.rs
raiden/examples/query.rs
raiden/examples/scan_with_filter.rs
raiden/examples/update.rs
raiden/src/condition/mod.rs
raiden/src/filter_expression/mod.rs
raiden/src/key_condition/mod.rs
raiden/tests/all/put.rs
raiden/tests/all/scan.rs
setup/fixtures/scan_with_filter_test_data_0.ts
setup/setup.ts

Support filter expression.
NA
NA
NA

feat: Support filter expression for query/scan

---

raiden-derive/src/condition/builder.rs
raiden/src/condition/mod.rs
raiden/src/filter_expression/mod.rs
raiden/src/key_condition/mod.rs
raiden/tests/all/condition.rs

chore: rename

---

Cargo.lock
raiden-derive/Cargo.toml
raiden-derive/src/attribute/names.rs
raiden/Cargo.toml
raiden/examples/get_with_reserved.rs
raiden/tests/all/get.rs

support reserved keywords
```rs
#[derive(Raiden)]
pub struct Reserved {
#[raiden(partition_key)]
id: String,
r#type: String,
}
```
[#96](https://github.com/raiden-rs/raiden-dynamo/issues/96)

add: support reserved keywords

---

raiden-derive/src/ops/shared.rs

fix: support default for null

---

raiden/examples/get_with_retries.rs
raiden/src/retry/mod.rs
raiden/tests/all/get.rs
raiden/tests/all/transact_write.rs

remove unused retry count
NA
NA
NA

fix: remove retry count

---

raiden/tests/all/get.rs
setup/fixtures/use_default_for_null_data.ts
setup/setup.ts

Add use_default test for null
NA
NA
NA

spec: Add test for null

---

raiden-derive/src/ops/query.rs

fix: impl retry for query

---

raiden/src/lib.rs
raiden/tests/all/get.rs

Support BTreeset for string/numberSet.
- NA
-NA
- NA

feat: Support btree set

---

raiden-derive/src/ops/put.rs

make field in XxxPutItemInput to public

refactor: make field in PutItemInput to public

---

raiden-derive/src/ops/put.rs
raiden-derive/src/ops/query.rs
raiden-derive/src/ops/update.rs

feat: add retry for update

---

raiden-derive/src/ops/put.rs
raiden-derive/src/ops/transact_write.rs

Remove unnecessary clone

---

raiden-derive/src/ops/put.rs
raiden-derive/src/ops/shared.rs
raiden/src/lib.rs

Support resolve item

---

raiden-derive/src/ops/transact_write.rs

Reverts raiden-rs/raiden-dynamo#213

Revert "Remove unnecessary clone"

---

raiden/src/filter_expression/mod.rs
raiden/tests/all/filter_expression.rs
raiden/tests/all/query.rs

Add support of the IN query filter to filter the result by a list of attributes.

Support IN filter

---

Cargo.lock
makefile
raiden-derive/Cargo.toml
raiden-derive/src/finder/mod.rs
raiden/Cargo.toml
raiden/src/next_token/mod.rs

Reverts raiden-rs/raiden-dynamo#224

Revert "chore: update and upgrade dependencies"

---

Cargo.lock
makefile
raiden-derive/Cargo.toml
raiden-derive/src/finder/mod.rs
raiden/Cargo.toml
raiden/src/next_token/mod.rs

Reverts raiden-rs/raiden-dynamo#233

Revert "Revert "chore: update and upgrade dependencies""
