raiden-rs/raiden-dynamo

raiden-derive/src/lib.rs

Use string instead of ident for table_name to use kebab-case
None
None
None

fix: Use string instead of ident for table_name to use kebab-case

---

raiden-derive/src/ops/get.rs
raiden-derive/src/ops/query.rs
raiden/examples/query.rs
raiden/tests/all/get.rs
raiden/tests/all/query.rs
raiden/tests/all/rename.rs
raiden/tests/all/rename_all.rs

I use `#struct_name` for get/query output item instead of `format_ident!("{}QueryOutput", struct_name` or `format_ident!("{}GetItemOutput", struct_name`. I think It makes more simple. FYI @kuy  
NA
NA
NA

fix: Use entity struct instead of Get/QueryOutputItem struct when get

---

.github/workflows/ci.yml

Use `actions/cache@v2` instead of `actions/cache@v1`.
- https://github.com/actions/cache/releases/tag/v2.0.0
N/A
N/A

Use actions/cache@v2 for speed up

---

raiden-derive/src/ops/shared.rs
raiden/examples/put.rs
raiden/src/lib.rs
raiden/tests/all/get.rs
raiden/tests/all/put.rs

I changed `FromAttribute` interface to support empty `HashSet` and `Vec`. 
- before
``` Rust
pub trait FromAttribute: Sized {
fn from_attr(value: AttributeValue) -> Result<Self, ()>;
}
```
- after
``` Rust
pub trait FromAttribute: Sized {
fn from_attr(value: Option<AttributeValue>) -> Result<Self, ()>;
}
```
It is able to return empty `HashSet` and `Vec` like following. when attribute not found. And user can define a behavior when attribute not found.However, I believe this change will affect #27. @kuy 
``` Rust
impl<A: FromAttribute + std::hash::Hash + std::cmp::Eq> FromAttribute
for std::collections::HashSet<A>
{
fn from_attr(value: Option<AttributeValue>) -> Result<Self, ()> {
if value.is_none() {
return Ok(std::collections::HashSet::new()); // An User can defined a behavior when item …
```

fix: FromAttribute interface to support empty hashSet and vec

---

raiden-derive/src/ops/put.rs
raiden-derive/src/ops/transact_write.rs
raiden/src/lib.rs
raiden/tests/all/put.rs

Ignore empty attributeValue to pass empty set and vec when put

fix: Ignore empty attributeValue to pass empty set and vec put

---

README.md
raiden-derive/src/ops/delete.rs
raiden-derive/src/ops/get.rs
raiden-derive/src/ops/update.rs
raiden/examples/delete.rs
raiden/tests/all/delete.rs
raiden/tests/all/get.rs
raiden/tests/all/update.rs
setup/index.js

This changes give a heads up about a missing sort key in compile time, not runtime.
```rust
let res = client.get("id1").run().await; // error 🔥 
let res = client.get("id1", 2003).run().await; // awesome 🚀 
```
```rust
let res = client.get("id1").sort_key(2003).run().await;
```
```rust
let res = client.get("id1", 2003).run().await;
```
```rust
let res = client.delete("id0").sort_key(2003).run().await;
```
```rust
let res = client.delete("id0", 2003).run().await;
```
```rust
let res = client
.update("id0")
.sort_key(36)
.set(set_expression)
....
```
```rust
let res = client
.update("id0", 36)
.set(set_expression)
....
```
*NOTE: No change in tables only partition key*
https://github.com/raiden-rs/raiden/issues/26
See [test code](https://github.com/raiden-rs/raiden/pull/46/files#diff-f30a3f3d …

Improve type check of sort key

---

raiden-derive/src/lib.rs
raiden-derive/src/ops/transact_write.rs
raiden/src/ops/transact_write.rs
raiden/src/update_expression/set.rs
raiden/tests/all/mod.rs
raiden/tests/all/transact_write.rs
setup/index.js

Support `update` for txWrite.
``` Rust
let input = User::put_item_builder()
.id("testId".to_owned())
.name("bokuweb".to_owned())
.build()
.unwrap();
let set_expression = User::update_expression()
.set(User::name())
.value("updated!!");
let res = tx
.put(User::put(input))
.update(User::update("testId2").set(set_expression))
.run()
.await;
```

feat: Add update for txWrite for now

---

raiden/src/lib.rs
raiden/tests/all/get.rs
raiden/tests/all/put.rs
setup/index.js

#58 improve empty string behavior.
If string is empty, raiden replace it to `NULL`.
``` Rust
impl IntoAttribute for String {
fn into_attr(self: Self) -> AttributeValue {
if self == "" {
// See. https://github.com/raiden-rs/raiden-dynamo/issues/58
return AttributeValue {
null: Some(true),
..Default::default()
};
}
AttributeValue {
s: Some(self),
..AttributeValue::default()
}
}
}
impl FromAttribute for String {
fn from_attr(value: Option<AttributeValue>) -> Result<Self, ()> {
if value.is_none() {
return Err(());
}
let value = value.unwrap();
if let Some(true) = value.null {
// See. https://github.com/raiden-rs/raiden/issues/58
return Ok("".to_owned());
}
value.s.ok_or((/* TODO: Add convert error handling */))
}
}
```
NA
NA
NA

feat: improve empty string behavior #58

---

raiden/src/update_expression/set.rs
raiden/tests/all/update.rs

Remove `value.null.is_some()` from delete condition.
A convert error caused by this condtion.
This is because if you write `Set` expression to empty string, string field is deleted by `Delete` expression.
NA
NA
https://github.com/raiden-rs/raiden-dynamo/pull/83/files#diff-cbeac8ecc7bb9c2e5969458d5c08fccbR363

fix: use delete expression when default attribute value

---

raiden/src/lib.rs

Fix empty string behavior
https://aws.amazon.com/jp/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/
NA
NA

fix: empty str behavior

---

raiden-derive/src/ops/shared.rs
raiden/src/lib.rs
raiden/tests/all/get.rs
setup/index.js

Support `use_default`. You can use this attribute if you want to assign default value if dynamo item value is none.
``` Rust
#[derive(Raiden)]
#[derive(Debug, Clone, PartialEq)]
pub struct UseDefault {
#[raiden(partition_key)]
id: String,
#[raiden(use_default)]
is_ok: bool,
}
```
NA
NA
NA

support use default #93

---

raiden-derive/src/ops/transact_write.rs
raiden/src/condition/mod.rs
raiden/src/ops/transact_write.rs
raiden/tests/all/transact_write.rs
setup/index.js

Support tx condition check.
``` Rust
let tx = ::raiden::WriteTx::new(Region::Custom {
endpoint: "http://localhost:8000".into(),
name: "ap-northeast-1".into(),
});
let input = TxConditionalCheckTestData0::put_item_builder()
.id("testId0".to_owned())
.name("bokuweb".to_owned())
.build();
let cond = TxConditionalCheckTestData1::condition()
.attr_exists(TxConditionalCheckTestData1::id());
tx.put(TxConditionalCheckTestData0::put(input))
.condition_check(
TxConditionalCheckTestData1::condition_check("id1").condition(cond)
)
.run()
.await;
```
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html
NA
NA

Support tx conditional check

---

Cargo.lock
raiden/examples/put.rs
raiden/src/lib.rs
raiden/tests/all/get.rs
raiden/tests/all/put.rs

Resolve errors reported by clippy.
- Use `is_empty()` built-in method
- Define custom error `ConversionError` and use in `FromAttribute` and `FromStringSetItem` trait

Use is_empty() to resolve clippy errors

---

Cargo.lock
raiden/Cargo.toml

Update `tokio` to `1.0.2` and `rusoto` to `0.46`. `Cargo.lock` has `libc 0.2.69`, but latest `mio` crate requires `TCP_KEEPINTVL` constant which defined in latest `libc`. So I also updated `libc` to `0.2.82` using `cargo update -p libc --precise 0.2.82`.
https://github.com/raiden-rs/raiden-dynamo/issues/110

Upgrade to Tokio 1.0 and Rusoto 0.46

---

raiden-derive/src/key_condition/builder.rs
raiden-derive/src/ops/query.rs
raiden/src/key_condition/mod.rs
raiden/tests/all/key_condition.rs
raiden/tests/all/query.rs
setup/index.js

Support `begins_with` function.
We can use `begins_with` like following if merged.
``` Rust
let cond = QueryTestData1::key_condition(QueryTestData1::id())
.eq("id0")
.and(QueryTestData1::key_condition(QueryTestData1::name()).begins_with("j"));
let res = client.query().key_condition(cond).run().await;
```

Support begins with

---

raiden/src/next_token/mod.rs

NextToken might be needed to convert to String with `.to_string()` in some case, so implements fmt::Display.
None
none
This is not a bug fix.

Implement display for NextToken

---

setup/deps.ts

Change CDN, and change aws-sdk version(for test).
No dependency version error has been fixed in version 3.39.0 .
- https://github.com/raiden-rs/raiden-dynamo/issues/160
- https://github.com/aws/aws-sdk-js-v3/issues/2810

fix test setup

---

raiden/src/filter_expression/mod.rs
raiden/src/lib.rs
raiden/tests/all/filter_expression.rs
raiden/tests/all/query.rs
raiden/tests/all/scan.rs
setup/fixtures/query_test_data_0.ts
setup/fixtures/scan_with_filter_test_data_0.ts

This PR is for adding the following operators to the filter expression.
- `OR` expression
- `attribute_exists` function
- `attribute_not_exists` function
- `attribute_type` function
- `contains` function
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html#Expressions.OperatorsAndFunctions.Syntax

Add operators for filter expression

---

raiden-derive/src/lib.rs
raiden/examples/with_http_client.rs

added `client_with` to raiden struct to use `rusoto::Client`.
this allows to select CredentialProviders like below.
https://github.com/raiden-rs/raiden-dynamo/blob/014328e400948f54987ad0f91a1046ed23313713/raiden/examples/with_http_client.rs#L19-L30

add client_with to struct

---

raiden/examples/transact_write_with_http_client.rs
raiden/src/ops/transact_write.rs

added `new_with_client` to `WriteTx` struct to use rusoto::Client.
this allows to select CredentialProviders like below.
https://github.com/yuntara/raiden-dynamo/blob/6669b22241c6ba18d3a84152cf51a96304070cf2/raiden/examples/transact_write_with_http_client.rs#L14-L26
https://github.com/raiden-rs/raiden-dynamo/pull/202

Add new_with_client to WriteTx

---

raiden/src/retry/mod.rs

Add a condition to retry when `HttpDispatchError`  and `CredentialsError` occurred.
NA
NA
NA

fix: retry condition

---

raiden/src/update_expression/set.rs
raiden/tests/all/update.rs

Utilised DynamoDB's [`if_not_exists` function](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.PreventingAttributeOverwrites) when updating an attribute.
- [AWS DynamoDB: Update expressions — Preventing overwrites of an existing attribute](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.PreventingAttributeOverwrites)

Implement if_not_exists for update

---

raiden-derive/src/ops/update.rs

Expand visibility of `update_expression` related methods (set, add, delete)

feat: public update_expression methods

---

raiden-derive/src/ops/shared.rs
raiden/tests/all/get.rs

- Fixed a compile error when using the use_default attribute for Generic Data Types.
N/A
N/A
N/A

fix: enable to use attribute use_default for generic type.

---

.github/workflows/ci.yml
Cargo.lock
raiden-derive/Cargo.toml
raiden-derive/src/ops/batch_delete.rs
raiden-derive/src/ops/batch_get.rs
raiden-derive/src/ops/delete.rs
raiden-derive/src/ops/scan.rs
raiden/Cargo.toml

- Enable to use retry policy in all operations.
- update dependencies.
- N/A
- N/A
- N/A
This pull request introduces enhanced retry support and more flexible error handling for DynamoDB operations in the `raiden-derive` crate. The changes refactor the generated code for batch and single-item operations to accept retry policies and conditions, and to perform retries using these policies. Additionally, the code is updated for improved consistency and maintainability, including updates to dependencies and minor workflow adjustments.
**Retry and Error Handling Improvements:**
* All builder structs for batch and single-item operations (`batch_get`, `batch_delete`, `delete_item`, `scan`) now include `policy` and `condition` fields, allowing for customizable retry logic. The `run` methods have …

chore: enable to retry in all operations.
